name          'eolsen-rancid'
version       '0.2.0'
source        'http://github.com/eoly/puppet-rancid'
author        'eolsen'
license       'Apache 2.0'
summary       'Manage RANCID'
description   'Manages RANCID including configuring your devices in their groups router.db files.'
project_page  'https://github.com/eoly/puppet-rancid'

dependency 'puppetlabs/stdlib', '>=3.2.0'
